# Generated by Django 4.2.11 on 2026-04-17 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('gross_requirement', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('projected_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('planned_order', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_results', to='inventory.item')),
            ],
            options={
                'verbose_name': 'MRP Result',
                'verbose_name_plural': 'MRP Results',
                'ordering': ['month'],
                'unique_together': {('item', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'ordering': ['month'],
                'unique_together': {('item', 'month')},
            },
        ),
    ]
