# Generated by Django 4.2.11 on 2026-04-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('inventory', '0002_item_lead_time_days'),
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('received', 'Received')], default='ordered', max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='inventory.item')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Pipeline Item',
                'verbose_name_plural': 'Pipeline Items',
                'ordering': ['-order_date'],
            },
        ),
    ]
