# Generated by Django 4.2.11 on 2026-04-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_category', models.CharField(max_length=50)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Value',
                'verbose_name_plural': 'Category Values',
                'ordering': ['-total_value'],
            },
        ),
        migrations.CreateModel(
            name='ValuationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('local_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('foreign_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_items', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Valuation Summary',
                'verbose_name_plural': 'Valuation Summaries',
            },
        ),
        migrations.CreateModel(
            name='StockValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('local_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('foreign_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Stock Valuation',
                'verbose_name_plural': 'Stock Valuations',
            },
        ),
    ]
