# Generated by Django 4.2.11 on 2026-04-17 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cd', models.DecimalField(decimal_places=2, default=0, help_text='Customs Duty %', max_digits=5)),
                ('rd', models.DecimalField(decimal_places=2, default=0, help_text='Regulatory Duty %', max_digits=5)),
                ('sd', models.DecimalField(decimal_places=2, default=0, help_text='Supplementary Duty %', max_digits=5)),
                ('vat', models.DecimalField(decimal_places=2, default=0, help_text='VAT %', max_digits=5)),
                ('ait', models.DecimalField(decimal_places=2, default=0, help_text='Advance Income Tax %', max_digits=5)),
                ('at', models.DecimalField(decimal_places=2, default=0, help_text='Advance Tax %', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hs_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HS Code',
                'verbose_name_plural': 'HS Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemHSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='duty.hscode')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hs_code_link', to='inventory.item')),
            ],
        ),
    ]
