# Generated by Django 4.2.11 on 2026-04-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lead_time_days',
            field=models.IntegerField(blank=True, help_text='Default lead time in days', null=True),
        ),
    ]
