# Generated by Django 4.2.11 on 2026-04-17 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity of child needed per parent', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(help_text='The raw material/component', on_delete=django.db.models.deletion.CASCADE, related_name='bom_as_child', to='inventory.item')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_entries', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(help_text='The finished/semi-finished good', on_delete=django.db.models.deletion.CASCADE, related_name='bom_as_parent', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Bill of Materials Entry',
                'verbose_name_plural': 'Bill of Materials',
                'ordering': ['parent', 'child'],
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
